@extends('layouts.app')

@section('title', 'Target Indikator')

@section('content')
    <div class="mx-auto max-w-[96rem] space-y-6">
        <header class="rounded-[2rem] border border-slate-200 bg-white px-6 py-8 shadow-[0_24px_80px_rgba(15,23,42,0.10)] sm:px-8">
            <div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold tracking-[0.22em] text-[#1f4b75] uppercase">Tolak Ukur</p><h1 class="mt-3 text-3xl font-semibold text-[#1f3550] sm:text-4xl">Target Indikator</h1><p class="mt-4 max-w-3xl text-sm leading-7 text-slate-600">Kelola target regulatif atau internal untuk KPI evaluasi pada setiap tahun berlaku.</p></div><a href="{{ route('admin.target-indikator.create') }}" class="inline-flex shrink-0 items-center justify-center rounded-xl bg-[#1f4b75] px-5 py-3 text-sm font-medium text-white hover:bg-[#173a5c] focus:outline-none focus:ring-4 focus:ring-[#b9cddd]">Tambah Target</a></div>
        </header>
        <x-flash-messages />

        <section class="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6" aria-labelledby="filter-target-title">
            <h2 id="filter-target-title" class="text-lg font-semibold text-slate-900">Filter target</h2>
            <form method="get" action="{{ route('admin.target-indikator.index') }}" class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                <div><label for="search" class="mb-2 block text-sm font-medium text-slate-700">Pencarian</label><input id="search" name="search" type="search" value="{{ $filters['search'] }}" placeholder="Kode, nama, atau sumber" class="w-full rounded-xl border border-slate-300 px-4 py-3 text-sm outline-none focus:border-[#1f4b75] focus:ring-4 focus:ring-[#dbe6ef]"></div>
                <div><label for="tahun" class="mb-2 block text-sm font-medium text-slate-700">Tahun</label><select id="tahun" name="tahun" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-[#1f4b75] focus:ring-4 focus:ring-[#dbe6ef]"><option value="">Semua Tahun</option>@foreach($tahunOptions as $tahun)<option value="{{ $tahun }}" @selected((int) $filters['tahun'] === (int) $tahun)>{{ $tahun }}</option>@endforeach</select></div>
                <div><label for="kode_indikator" class="mb-2 block text-sm font-medium text-slate-700">Indikator</label><select id="kode_indikator" name="kode_indikator" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-[#1f4b75] focus:ring-4 focus:ring-[#dbe6ef]"><option value="">Semua Indikator</option>@foreach($indikatorOptions as $code => $name)<option value="{{ $code }}" @selected($filters['kode_indikator'] === $code)>{{ $code }}</option>@endforeach</select></div>
                <div><label for="jenis_target" class="mb-2 block text-sm font-medium text-slate-700">Jenis</label><select id="jenis_target" name="jenis_target" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-[#1f4b75] focus:ring-4 focus:ring-[#dbe6ef]"><option value="">Semua Jenis</option><option value="Regulatif" @selected($filters['jenis_target'] === 'Regulatif')>Regulatif</option><option value="Internal" @selected($filters['jenis_target'] === 'Internal')>Internal</option></select></div>
                <div><label for="status_aktif" class="mb-2 block text-sm font-medium text-slate-700">Status</label><select id="status_aktif" name="status_aktif" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-[#1f4b75] focus:ring-4 focus:ring-[#dbe6ef]"><option value="">Semua Status</option><option value="1" @selected($filters['status_aktif'] === '1')>Aktif</option><option value="0" @selected($filters['status_aktif'] === '0')>Nonaktif</option></select></div>
                <div><label for="sort" class="mb-2 block text-sm font-medium text-slate-700">Urutkan</label><select id="sort" name="sort" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-[#1f4b75] focus:ring-4 focus:ring-[#dbe6ef]">@foreach($sortOptions as $value => $label)<option value="{{ $value }}" @selected($filters['sort'] === $value)>{{ $label }}</option>@endforeach</select></div>
                <div><label for="direction" class="mb-2 block text-sm font-medium text-slate-700">Arah</label><select id="direction" name="direction" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-[#1f4b75] focus:ring-4 focus:ring-[#dbe6ef]"><option value="asc" @selected($filters['direction'] === 'asc')>Naik</option><option value="desc" @selected($filters['direction'] === 'desc')>Turun</option></select></div>
                <div class="flex items-end gap-2"><button type="submit" class="inline-flex flex-1 justify-center rounded-xl bg-[#1f4b75] px-4 py-3 text-sm font-medium text-white hover:bg-[#173a5c] focus:outline-none focus:ring-4 focus:ring-[#b9cddd]">Terapkan</button><a href="{{ route('admin.target-indikator.index') }}" class="rounded-xl border border-slate-300 px-4 py-3 text-sm font-medium text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-4 focus:ring-[#dbe6ef]">Reset</a></div>
            </form>
        </section>

        <section class="overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white shadow-sm" aria-labelledby="daftar-target-title">
            <div class="border-b border-slate-200 px-6 py-5"><h2 id="daftar-target-title" class="text-lg font-semibold text-slate-900">Daftar Target</h2><p class="mt-1 text-sm text-slate-500">{{ $targetIndikators->total() }} data ditemukan.</p></div>
            @if($targetIndikators->isEmpty())
                <div class="p-6"><x-empty-state title="Target indikator belum tersedia" description="Belum ada target yang sesuai dengan filter. Tambahkan target hanya jika sumber penetapannya tersedia." /></div>
            @else
                <div class="overflow-x-auto"><table class="min-w-[72rem] divide-y divide-slate-200 text-left text-sm"><caption class="sr-only">Daftar target indikator</caption><thead class="bg-slate-50 text-slate-600"><tr><th scope="col" class="px-5 py-3 font-medium">Indikator</th><th scope="col" class="px-5 py-3 font-medium">Tahun</th><th scope="col" class="px-5 py-3 font-medium">Target</th><th scope="col" class="px-5 py-3 font-medium">Arah</th><th scope="col" class="px-5 py-3 font-medium">Jenis</th><th scope="col" class="px-5 py-3 font-medium">Sumber</th><th scope="col" class="px-5 py-3 font-medium">Status</th><th scope="col" class="px-5 py-3 font-medium">Aksi</th></tr></thead><tbody class="divide-y divide-slate-200">
                    @foreach($targetIndikators as $target)<tr class="hover:bg-slate-50/70"><th scope="row" class="px-5 py-4"><span class="block font-semibold text-[#1f3550]">{{ $target->kode_indikator }}</span><span class="mt-1 block max-w-xs text-xs font-normal leading-5 text-slate-500">{{ $target->nama_indikator }}</span></th><td class="px-5 py-4">{{ $target->tahun_berlaku }}</td><td class="px-5 py-4 font-semibold text-slate-900">{{ number_format((float) $target->nilai_target, 2, ',', '.') }}%</td><td class="px-5 py-4 text-slate-600">{{ $target->arah_target }}</td><td class="px-5 py-4 text-slate-600">{{ $target->jenis_target }}</td><td class="px-5 py-4 text-slate-600">{{ $target->sumber_target ?: '-' }}</td><td class="px-5 py-4"><x-status-badge :status="$target->status_aktif ? 'Aktif' : 'Nonaktif'" :tone="$target->status_aktif ? 'Hijau' : 'Abu-abu'" /></td><td class="px-5 py-4"><div class="flex flex-wrap gap-2"><a href="{{ route('admin.target-indikator.show', $target) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-xs font-medium text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-4 focus:ring-[#dbe6ef]">Detail</a><a href="{{ route('admin.target-indikator.edit', $target) }}" class="rounded-lg border border-blue-200 px-3 py-2 text-xs font-medium text-[#1f4b75] hover:bg-blue-50 focus:outline-none focus:ring-4 focus:ring-[#dbe6ef]">Ubah</a><form action="{{ route('admin.target-indikator.destroy', $target) }}" method="post" onsubmit="return confirm('Yakin ingin menghapus target indikator ini?')">@csrf @method('DELETE')<button type="submit" class="rounded-lg border border-red-200 px-3 py-2 text-xs font-medium text-red-600 hover:bg-red-50 focus:outline-none focus:ring-4 focus:ring-red-100">Hapus</button></form></div></td></tr>@endforeach
                </tbody></table></div><div class="border-t border-slate-200 px-5 py-4">{{ $targetIndikators->links() }}</div>
            @endif
        </section>
    </div>
@endsection
