@extends('layouts.app')
@section('title', 'Detail Target Indikator')
@section('content')
    <div class="mx-auto max-w-5xl space-y-6">
        <header class="rounded-[2rem] border border-slate-200 bg-white px-6 py-8 shadow-[0_24px_80px_rgba(15,23,42,0.10)] sm:px-8"><div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold tracking-[0.22em] text-[#1f4b75] uppercase">Detail Target</p><h1 class="mt-3 text-3xl font-semibold text-[#1f3550] sm:text-4xl">{{ $targetIndikator->kode_indikator }}</h1><p class="mt-3 text-sm leading-6 text-slate-600">{{ $targetIndikator->nama_indikator }}</p></div><div class="flex gap-2"><a href="{{ route('admin.target-indikator.index') }}" class="rounded-xl border border-slate-300 px-4 py-3 text-sm font-medium text-slate-700 hover:bg-slate-50 focus:outline-none focus:ring-4 focus:ring-[#dbe6ef]">Kembali</a><a href="{{ route('admin.target-indikator.edit', $targetIndikator) }}" class="rounded-xl bg-[#1f4b75] px-4 py-3 text-sm font-medium text-white hover:bg-[#173a5c] focus:outline-none focus:ring-4 focus:ring-[#b9cddd]">Ubah</a></div></div></header>
        <x-flash-messages />
        <section class="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><dl class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div class="rounded-xl bg-slate-50 p-4"><dt class="text-xs text-slate-500">Tahun Berlaku</dt><dd class="mt-2 text-xl font-semibold text-[#1f3550]">{{ $targetIndikator->tahun_berlaku }}</dd></div><div class="rounded-xl bg-slate-50 p-4"><dt class="text-xs text-slate-500">Nilai Target</dt><dd class="mt-2 text-xl font-semibold text-[#1f3550]">{{ number_format((float) $targetIndikator->nilai_target, 4, ',', '.') }}%</dd></div><div class="rounded-xl bg-slate-50 p-4"><dt class="text-xs text-slate-500">Status</dt><dd class="mt-2"><x-status-badge :status="$targetIndikator->status_aktif ? 'Aktif' : 'Nonaktif'" :tone="$targetIndikator->status_aktif ? 'Hijau' : 'Abu-abu'" /></dd></div><div class="rounded-xl bg-slate-50 p-4"><dt class="text-xs text-slate-500">Arah Target</dt><dd class="mt-2 font-semibold text-slate-900">{{ $targetIndikator->arah_target }}</dd></div><div class="rounded-xl bg-slate-50 p-4"><dt class="text-xs text-slate-500">Jenis Target</dt><dd class="mt-2 font-semibold text-slate-900">{{ $targetIndikator->jenis_target }}</dd></div><div class="rounded-xl bg-slate-50 p-4"><dt class="text-xs text-slate-500">Sumber</dt><dd class="mt-2 font-semibold leading-6 text-slate-900">{{ $targetIndikator->sumber_target ?: 'Tidak dicantumkan' }}</dd></div></dl></section>
        <aside class="rounded-[1.5rem] border border-blue-200 bg-blue-50 p-5 text-sm leading-6 text-blue-900">Untuk arah Minimize, nilai aktual yang sama dengan atau lebih rendah dari target dinilai memenuhi tolak ukur.</aside>
        <div class="flex justify-end"><form action="{{ route('admin.target-indikator.destroy', $targetIndikator) }}" method="post" onsubmit="return confirm('Yakin ingin menghapus target indikator ini?')">@csrf @method('DELETE')<button type="submit" class="rounded-xl border border-red-300 px-5 py-3 text-sm font-medium text-red-700 hover:bg-red-50 focus:outline-none focus:ring-4 focus:ring-red-100">Hapus Target</button></form></div>
    </div>
@endsection
